remote_theme: daattali/beautiful-jekyll


title: Pravara Partners

author: Pravara Partners

navbar-links:
  About: "/#aboutus"
  Values: "/#clients"
  Contact: "/contact"

title-img:

site-css: "/assets/css/main.css"

#keywords: "r shiny,shiny developer,shiny consultant,r consultant,shiny apps"

mobile-theme-col: "#0085A1"
navbar-col: "#05172d"
navbar-text-col: "#fff"
navbar-border-col: "#05172d"

social-network-links:
  email: "info@pravarapartners.com"

url-pretty: "pravarapartners.com"

footer-img: "/assets/img/footer-bg.png"

gtag: ""

timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      nav-short: true
      share-description: "Add a description here."

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md


plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
